version: '3.7'

services:
  api:
    container_name:  "apigo"
    # we want to use the image which is build from our Dockerfile
    build: .
    ports:
      - "8080:8080"
    # we are depending on the mysql backend
    depends_on:
      - db
    # We mount the working dir into the container, handy for development
    # This is what makes the hot reloading work inside of a Docker container
    volumes:
      - .:/app/
    environment:
      - POSTGRES_USER=bucketeer
      - POSTGRES_PASSWORD=bucketeer_pass
      - POSTGRES_DB=bucketeer_db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=bucketeer
      - POSTGRES_PASSWORD=bucketeer_pass
      - POSTGRES_DB=bucketeer_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: